apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: goweb
        release: stable
        environment: production
    spec:
      containers:
      - name: goweb
        image: darek/goweb:1.0
        ports:
        - containerPort: 8080
